### ISSUE TITLE
Feature Request: Pressing the up arrow repeats the last command

### ISSUE THREAD

**Issue by erawhctim** [eliascotto/tryclojure#26]
Would be useful to recall the last command (if it was misspelled, etc.) vs. typing it all out again, especially for beginners to the syntax 🙂 

Great tool!

**Comment by eliascotto** [comment]
You can do that pressing arrow up, as you would do in a REPL. Is it not
working for you?

**Comment by erawhctim** [comment]
Hmm, it looks like pressing up works to "queue" up the last command, and hitting enter will execute it, but I don't actually see the last command listed in the text field after pressing up. 

So I guess it does work (only slightly?)
